/*
    Plugin-SDK (Grand Theft Auto San Andreas) header file
    Authors: GTA Community. See more here
    https://github.com/DK22Pac/plugin-sdk
    Do not delete this comment block. Respect others' work!
*/
#pragma once

enum eWeaponType : unsigned int
{
	WEAPONTYPE_UNARMED = 0x0,
	WEAPONTYPE_BRASSKNUCKLE = 0x1,
	WEAPONTYPE_GOLFCLUB = 0x2,
	WEAPONTYPE_NIGHTSTICK = 0x3,
	WEAPONTYPE_KNIFE = 0x4,
	WEAPONTYPE_BASEBALLBAT = 0x5,
	WEAPONTYPE_SHOVEL = 0x6,
	WEAPONTYPE_POOLCUE = 0x7,
	WEAPONTYPE_KATANA = 0x8,
	WEAPONTYPE_CHAINSAW = 0x9,
	WEAPONTYPE_DILDO1 = 0xA,
	WEAPONTYPE_DILDO2 = 0xB,
	WEAPONTYPE_VIBE1 = 0xC,
	WEAPONTYPE_VIBE2 = 0xD,
	WEAPONTYPE_FLOWERS = 0xE,
	WEAPONTYPE_CANE = 0xF,
	WEAPONTYPE_GRENADE = 0x10,
	WEAPONTYPE_TEARGAS = 0x11,
	WEAPONTYPE_MOLOTOV = 0x12,
	WEAPONTYPE_ROCKET = 0x13,
	WEAPONTYPE_ROCKET_HS = 0x14,
	WEAPONTYPE_FREEFALL_BOMB = 0x15,
	WEAPONTYPE_PISTOL = 0x16,
	WEAPONTYPE_PISTOL_SILENCED = 0x17,
	WEAPONTYPE_DESERT_EAGLE = 0x18,
	WEAPONTYPE_SHOTGUN = 0x19,
	WEAPONTYPE_SAWNOFF = 0x1A,
	WEAPONTYPE_SPAS12 = 0x1B,
	WEAPONTYPE_MICRO_UZI = 0x1C,
	WEAPONTYPE_MP5 = 0x1D,
	WEAPONTYPE_AK47 = 0x1E,
	WEAPONTYPE_M4 = 0x1F,
	WEAPONTYPE_TEC9 = 0x20,
	WEAPONTYPE_COUNTRYRIFLE = 0x21,
	WEAPONTYPE_SNIPERRIFLE = 0x22,
	WEAPONTYPE_RLAUNCHER = 0x23,
	WEAPONTYPE_RLAUNCHER_HS = 0x24,
	WEAPONTYPE_FTHROWER = 0x25,
	WEAPONTYPE_MINIGUN = 0x26,
	WEAPONTYPE_SATCHEL_CHARGE = 0x27,
	WEAPONTYPE_DETONATOR = 0x28,
	WEAPONTYPE_SPRAYCAN = 0x29,
	WEAPONTYPE_EXTINGUISHER = 0x2A,
	WEAPONTYPE_CAMERA = 0x2B,
	WEAPONTYPE_NIGHTVISION = 0x2C,
	WEAPONTYPE_INFRARED = 0x2D,
	WEAPONTYPE_PARACHUTE = 0x2E,
	WEAPONTYPE_UNUSED = 0x2F,
	WEAPONTYPE_ARMOUR = 0x30,
	WEAPONTYPE_FLARE = 0x3A
};