/*
    Plugin-SDK (Grand Theft Auto 3) header file
    Authors: GTA Community. See more here
    https://github.com/DK22Pac/plugin-sdk
    Do not delete this comment block. Respect others' work!
*/
#pragma once

enum eGarageID : short {
    GARAGE_ID_CAR_CRUSHER = 0,
    GARAGE_ID_PORTLAND_HIDEOUT = 1,
    GARAGE_ID_PORTLAND_IE = 2,
    GARAGE_ID_PORTLAND_BOMBSHOP = 3,
    GARAGE_ID_PORTLAND_PAYNSPRAY = 4,
    GARAGE_ID_SALVATORES = 5,
    GARAGE_ID_SECURICAR = 6,
    GARAGE_ID_LUIGIS_LOCKUP = 7,
    GARAGE_ID_STAUNTON_HIDEOUT = 8,
    GARAGE_ID_STAUNTON_BOMSHOP = 9,
    GARAGE_ID_STAUNTON_PAYNSPRAY = 10,
    GARAGE_ID_RAY_LOCKUP = 11,
    GARAGE_ID_WITSEC_HOUSE = 12,
    GARAGE_ID_KENJI_LOCKUP = 13,
    GARAGE_ID_COLUMBIAN_GARAGE_1 = 14,
    GARAGE_ID_COLUMBIAN_GARAGE_2 = 15,
    GARAGE_ID_COLUMBIAN_GARAGE_3 = 16,
    GARAGE_ID_COLUMBIAN_GARAGE_4 = 17,
    GARAGE_ID_COLUMBIAN_GARAGE_5 = 18,
    GARAGE_ID_YARDIE_LOCKUP = 19,
    GARAGE_ID_SHORESIDE_HIDEOUT = 20,
    GARAGE_ID_SHORESIDE_PAYNSPRAY = 21,
    GARAGE_ID_SHORESIDE_BOMBSHOP = 22,
    GARAGE_ID_SHORESIDE_IE = 23,
    GARAGE_ID_HOODS_DEFUSAL = 24,
    GARAGE_ID_PLATINUM_DROPOFF = 25,
    GARAGE_ID_DONALD_LOVES_STASH = 26
};
