/*
    Plugin-SDK (Grand Theft Auto 3) header file
    Authors: GTA Community. See more here
    https://github.com/DK22Pac/plugin-sdk
    Do not delete this comment block. Respect others' work!
*/
#pragma once

enum eHandlingIndex : unsigned int {
    LANDSTAL = 0,
    IDAHO,
    STINGER,
    LINERUN,
    PEREN,
    SENTINEL,
    PATRIOT,
    FIRETRUK,
    TRASH,
    STRETCH,
    MANANA,
    INFERNUS,
    BLISTA,
    PONY,
    MULE,
    CHEETAH,
    AMBULAN,
    FBICAR,
    MOONBEAM,
    ESPERANT,
    TAXI,
    KURUMA,
    BOBCAT,
    MRWHOOP,
    BFINJECT,
    POLICE,
    ENFORCER,
    SECURICA,
    BANSHEE,
    PREDATOR,
    BUS,
    RHINO,
    BARRACKS,
    TRAIN,
    HELI,
    DODO,
    COACH,
    CABBIE,
    STALLION,
    RUMPO,
    RCBANDIT,
    BELLYUP,
    MRWONGS,
    MAFIA,
    YARDIE,
    YAKUZA,
    DIABLOS,
    COLUMB,
    HOODS,
    AIRTRAIN,
    DEADDODO,
    SPEEDER,
    REEFER,
    PANLANT,
    FLATBED,
    YANKEE,
    BORGNINE
};
