/*
    Plugin-SDK (Grand Theft Auto 3) header file
    Authors: GTA Community. See more here
    https://github.com/DK22Pac/plugin-sdk
    Do not delete this comment block. Respect others' work!
*/
#pragma once

enum eObjective {
    OBJECTIVE_NONE = 0,
    OBJECTIVE_IDLE = 1,
    OBJECTIVE_FLEE_TILL_SAFE = 2,
    OBJECTIVE_GUARD_SPOT = 3,
    OBJECTIVE_4 = 4,
    OBJECTIVE_WAIT_IN_CAR = 5,
    OBJECTIVE_6 = 6,
    OBJECTIVE_KILL_CHAR_ON_FOOT = 7,
    OBJECTIVE_KILL_CHAR_ANY_MEANS = 8,
    OBJECTIVE_FLEE_CHAR_ON_FOOT_TILL_SAFE = 9,
    OBJECTIVE_FLEE_CHAR_ON_FOOT_ALWAYS = 10,
    OBJECTIVE_GOTO_CHAR_ON_FOOT = 11,
    OBJECTIVE_FOLLOW_PED_IN_FORMATION = 12,
    OBJECTIVE_LEAVE_VEHICLE = 13,
    OBJECTIVE_ENTER_CAR_AS_PASSENGER = 14,
    OBJECTIVE_ENTER_CAR_AS_DRIVER = 15,
    OBJECTIVE_10 = 16,
    OBJECTIVE_11 = 17, 
    OBJECTIVE_12 = 18,
    OBJECTIVE_DESTROY_CAR = 19,
    OBJECTIVE_GOTO_AREA_ANY_MEANS = 20,
    OBJECTIVE_GOTO_AREA_ON_FOOT = 21,
    OBJECTIVE_RUN_TO_AREA = 22,
    OBJECTIVE_17 = 23,
    OBJECTIVE_18 = 24,
    OBJECTIVE_FIGHT_CHAR = 25,
    OBJECTIVE_FOLLOW_LEADER = 26,
    OBJECTIVE_FOLLOW_ROUTE = 27,
    OBJECTIVE_SOLICIT = 28,
    OBJECTIVE_HAIL_TAXI = 29,
    OBJECTIVE_CATCH_TRAIN = 30,
    OBJECTIVE_BUY_ICE_CREAM = 31,
    OBJECTIVE_STEAL_ANY_CAR = 32,
    OBJECTIVE_MUG_CHAR = 33,
    OBJECTIVE_FLEE_CAR = 34,
    OBJECTIVE_23 = 35
};