/*
Plugin-SDK (Grand Theft Auto 3) header file
Authors: GTA Community. See more here
https://github.com/DK22Pac/plugin-sdk
Do not delete this comment block. Respect others' work!
*/
#pragma once

enum ePedStats {
    PEDSTAT_PLAYER = 0,
    PEDSTAT_COP = 1,
    PEDSTAT_MEDIC = 2,
    PEDSTAT_FIRE = 3,
    PEDSTAT_GANG1 = 4,
    PEDSTAT_GANG2 = 5,
    PEDSTAT_GANG3 = 6,
    PEDSTAT_GANG4 = 7,
    PEDSTAT_GANG5 = 8,
    PEDSTAT_GANG6 = 9,
    PEDSTAT_GANG7 = 10,
    PEDSTAT_STREET_GUY = 11,
    PEDSTAT_SUIT_GUY = 12,
    PEDSTAT_SENSIBLE_GUY = 13,
    PEDSTAT_GEEK_GUY = 14,
    PEDSTAT_OLD_GUY = 15,
    PEDSTAT_TOUGH_GUY = 16,
    PEDSTAT_STREET_GIRL = 17,
    PEDSTAT_SUIT_GIRL = 18,
    PEDSTAT_SENSIBLE_GIRL = 19,
    PEDSTAT_GEEK_GIRL = 20,
    PEDSTAT_OLD_GIRL = 21,
    PEDSTAT_TOUGH_GIRL = 22,
    PEDSTAT_TRAMP_MALE = 23,
    PEDSTAT_TRAMP_FEMALE = 24,
    PEDSTAT_TOURIST = 25,
    PEDSTAT_PROSTITUTE = 26,
    PEDSTAT_CRIMINAL = 27,
    PEDSTAT_BUSKER = 28,
    PEDSTAT_TAXIDRIVER = 29,
    PEDSTAT_PSYCHO = 30,
    PEDSTAT_STEWARD = 31,
    PEDSTAT_SPORTSFAN = 32,
    PEDSTAT_SHOPPER = 33,
    PEDSTAT_OLDSHOPPER = 34
};