/*
    Plugin-SDK (Grand Theft Auto 3) header file
    Authors: GTA Community. See more here
    https://github.com/DK22Pac/plugin-sdk
    Do not delete this comment block. Respect others' work!
*/
#pragma once

#include "PluginBase.h"

enum PLUGIN_API ePedState {
    PEDSTATE_NONE = 0,
    PEDSTATE_IDLE = 1,
    PEDSTATE_LOOK_ENTITY = 2,
    PEDSTATE_LOOK_HEADING = 3,
    PEDSTATE_WANDER_RANGE = 4,
    PEDSTATE_WANDER_PATH = 5,
    PEDSTATE_SEEK_POSITION = 6,
    PEDSTATE_SEEK_ENTITY = 7,
    PEDSTATE_FLEE_POSITION = 8,
    PEDSTATE_FLEE_ENTITY = 9,
    PEDSTATE_PURSUE = 10,
    PEDSTATE_FOLLOW_PATH = 11,
    PEDSTATE_SNIPER_MODE = 12,
    PEDSTATE_ROCKET_MODE = 13,
    PEDSTATE_DUMMY = 14,
    PEDSTATE_PAUSE = 15,
    PEDSTATE_ATTACK = 16,
    PEDSTATE_FIGHT = 17,
    PEDSTATE_FACE_PHONE = 18,
    PEDSTATE_MAKE_PHONECALL = 19,
    PEDSTATE_CHAT = 20,
    PEDSTATE_MUG = 21,
    PEDSTATE_AIMGUN = 22,
    PEDSTATE_AI_CONTROL = 23,
    PEDSTATE_SEEK_CAR = 24,
    PEDSTATE_SEEK_IN_BOAT = 25,
    PEDSTATE_FOLLOW_ROUTE = 26,
    PEDSTATE_CPR = 27,
    PEDSTATE_SOLICIT = 28,
    PEDSTATE_BUY_ICECREAM = 29,
    PEDSTATE_INVESTIGATE = 30,
    PEDSTATE_STEP_AWAY = 31,
    PEDSTATE_ON_FIRE = 32,
    PEDSTATE_HANG_OUT = 33,
    PEDSTATE_STATES_NO_AI = 34,
    PEDSTATE_JUMP = 35,
    PEDSTATE_FALL = 36,
    PEDSTATE_GETUP = 37,
    PEDSTATE_STAGGER = 38,
    PEDSTATE_DIVE_AWAY = 39,
    PEDSTATE_CAN_SHOOT = 40,
    PEDSTATE_ENTER_TRAIN = 41,
    PEDSTATE_EXIT_TRAIN = 42,
    PEDSTATE_ARREST_PLAYER = 43,
    PEDSTATE_DRIVING = 44,
    PEDSTATE_PASSENGER = 45,
    PEDSTATE_TAXI_PASSENGER = 46,
    PEDSTATE_OPEN_DOOR = 47,
    PEDSTATE_DIE = 48,
    PEDSTATE_DEAD = 49,
    PEDSTATE_CARJACK = 50,
    PEDSTATE_DRAG_FROM_CAR = 51,
    PEDSTATE_ENTER_CAR = 52,
    PEDSTATE_STEAL_CAR = 53,
    PEDSTATE_EXIT_CAR = 54,
    PEDSTATE_HANDS_UP = 55,
    PEDSTATE_ARRESTED = 56
};
