/*
Plugin-SDK (Grand Theft Auto 3) header file
Authors: GTA Community. See more here
https://github.com/DK22Pac/plugin-sdk
Do not delete this comment block. Respect others' work!
*/
#pragma once

enum eWeaponType : unsigned int {
    WEAPONTYPE_UNARMED = 0,
    WEAPONTYPE_BASEBALLBAT,
    WEAPONTYPE_COLT45,
    WEAPONTYPE_UZI,
    WEAPONTYPE_SHOTGUN,
    WEAPONTYPE_AK47,
    WEAPONTYPE_M16,
    WEAPONTYPE_SNIPERRIFLE,
    WEAPONTYPE_ROCKETLAUNCHER,
    WEAPONTYPE_FLAMETHROWER,
    WEAPONTYPE_MOLOTOV,
    WEAPONTYPE_GRENADE,
    WEAPONTYPE_DETONATOR,
    WEAPONTYPE_HELICANNON,
    WEAPONTYPE_LAST_WEAPONTYPE,
    WEAPONTYPE_ARMOUR,
    WEAPONTYPE_RAMMEDBYCAR,
    WEAPONTYPE_RUNOVERBYCAR,
    WEAPONTYPE_EXPLOSION,
    WEAPONTYPE_UZI_DRIVEBY,
    WEAPONTYPE_DROWNING,
    WEAPONTYPE_FALL,
    WEAPONTYPE_UNIDENTIFIED,
};