#pragma once

const float FNC_NITROUS_BASE_ACCELERATION = 1.2f;
const float FNC_NITROUS_ACCELERATION_MULTIPLIER = 0.2f; // per 'boost' ; NitrousAcc = MULTIPLIER * numBoosts + BASE

bool  FNC_ENABLE_KEYBOARD_CONTROL = true;

bool  FNC_DRAW_V_HUD = false;

bool  FNC_DRAW_WIDESCREEN_PARAMETERS = false;

const float FNC_DRAW_NITROUS_BAR_POS_X  = 144.0f;
const float FNC_DRAW_NITROUS_BAR_POS_Y  = 110.0f;
const float FNC_DRAW_NITROUS_BAR_WIDTH = 9.0f;
const float FNC_DRAW_NITROUS_BAR_HEIGHT = 72.0f;
const float FNC_DRAW_NITROUS_TEXT_POS_X = 148.0;
const float FNC_DRAW_NITROUS_TEXT_POS_Y = 38.0f;
const float FNC_DRAW_NITROUS_TEXT_WIDTH = 0.3f;
const float FNC_DRAW_NITROUS_TEXT_HEIGHT = 0.7f;
const float FNC_DRAW_NITROUS_BAR_BORDER = 2.0f;

const float FNC_DRAW_WIDE_NITROUS_BAR_POS_X = 236.0f;
const float FNC_DRAW_WIDE_NITROUS_BAR_POS_Y = 216.0f;
const float FNC_DRAW_WIDE_NITROUS_BAR_WIDTH = 14.0f;
const float FNC_DRAW_WIDE_NITROUS_BAR_HEIGHT = 135.0f;
const float FNC_DRAW_WIDE_NITROUS_TEXT_POS_X = 243.0f;
const float FNC_DRAW_WIDE_NITROUS_TEXT_POS_Y = 78.0f;
const float FNC_DRAW_WIDE_NITROUS_TEXT_WIDTH = 0.6f;
const float FNC_DRAW_WIDE_NITROUS_TEXT_HEIGHT = 1.2f;
const float FNC_DRAW_WIDE_NITROUS_BAR_BORDER = 4.0f;

const float FNC_DRAW_VHUD_NITROUS_BAR_POS_X = 48.0f;
const float FNC_DRAW_VHUD_NITROUS_BAR_POS_Y = 25.0f;
const float FNC_DRAW_VHUD_NITROUS_BAR_WIDTH = 200.0f;
const float FNC_DRAW_VHUD_NITROUS_BAR_HEIGHT = 14.0f;
const float FNC_DRAW_VHUD_NITROUS_TEXT_POS_X = 262.0f;
const float FNC_DRAW_VHUD_NITROUS_TEXT_POS_Y = 29.0f;
const float FNC_DRAW_VHUD_NITROUS_TEXT_WIDTH = 0.5f;
const float FNC_DRAW_VHUD_NITROUS_TEXT_HEIGHT = 1.0f;
const float FNC_DRAW_VHUD_NITROUS_BAR_BORDER = 4.0f;