/*
    Plugin-SDK (Grand Theft Auto 3) header file
    Authors: GTA Community. See more here
    https://github.com/DK22Pac/plugin-sdk
    Do not delete this comment block. Respect others' work!
*/
#pragma once

#include "PluginBase.h"

enum PLUGIN_API eHandlingIndex : unsigned int {
    HANDLING_LANDSTAL = 0,
    HANDLING_IDAHO = 1,
    HANDLING_STINGER = 2,
    HANDLING_LINERUN = 3,
    HANDLING_PEREN = 4,
    HANDLING_SENTINEL = 5,
    HANDLING_PATRIOT = 6,
    HANDLING_FIRETRUK = 7,
    HANDLING_TRASH = 8,
    HANDLING_STRETCH = 9,
    HANDLING_MANANA = 10,
    HANDLING_INFERNUS = 11,
    HANDLING_BLISTA = 12,
    HANDLING_PONY = 13,
    HANDLING_MULE = 14,
    HANDLING_CHEETAH = 15,
    HANDLING_AMBULAN = 16,
    HANDLING_FBICAR = 17,
    HANDLING_MOONBEAM = 18,
    HANDLING_ESPERANT = 19,
    HANDLING_TAXI = 20,
    HANDLING_KURUMA = 21,
    HANDLING_BOBCAT = 22,
    HANDLING_MRWHOOP = 23,
    HANDLING_BFINJECT = 24,
    HANDLING_POLICE = 25,
    HANDLING_ENFORCER = 26,
    HANDLING_SECURICA = 27,
    HANDLING_BANSHEE = 28,
    HANDLING_PREDATOR = 29,
    HANDLING_BUS = 30,
    HANDLING_RHINO = 31,
    HANDLING_BARRACKS = 32,
    HANDLING_TRAIN = 33,
    HANDLING_HELI = 34,
    HANDLING_DODO = 35,
    HANDLING_COACH = 36,
    HANDLING_CABBIE = 37,
    HANDLING_STALLION = 38,
    HANDLING_RUMPO = 39,
    HANDLING_RCBANDIT = 40,
    HANDLING_BELLYUP = 41,
    HANDLING_MRWONGS = 42,
    HANDLING_MAFIA = 43,
    HANDLING_YARDIE = 44,
    HANDLING_YAKUZA = 45,
    HANDLING_DIABLOS = 46,
    HANDLING_COLUMB = 47,
    HANDLING_HOODS = 48,
    HANDLING_AIRTRAIN = 49,
    HANDLING_DEADDODO = 50,
    HANDLING_SPEEDER = 51,
    HANDLING_REEFER = 52,
    HANDLING_PANLANT = 53,
    HANDLING_FLATBED = 54,
    HANDLING_YANKEE = 55,
    HANDLING_BORGNINE = 56
};
