/*
Plugin-SDK (Grand Theft Auto Vice City) header file
Authors: GTA Community. See more here
https://github.com/DK22Pac/plugin-sdk
Do not delete this comment block. Respect others' work!
*/
#pragma once

enum ePedType : int
{
	PEDTYPE_PLAYER1 = 0,
	PEDTYPE_PLAYER2 = 1,
	PEDTYPE_PLAYER3 = 2,
	PEDTYPE_PLAYER4 = 3,
	PEDTYPE_CIVMALE = 4,
	PEDTYPE_CIVFEMALE = 5,
	PEDTYPE_COP = 6,
	PEDTYPE_GANG_CUBAN = 7,
	PEDTYPE_GANG_HAITIAN = 8,
	PEDTYPE_GANG_STREET = 9,
	PEDTYPE_GANG_DIAZ = 10,
	PEDTYPE_GANG_SECURITY = 11,
	PEDTYPE_GANG_BIKER = 12,
	PEDTYPE_GANG_PLAYER = 13,
	PEDTYPE_GANG_GOLFER = 14,
	PEDTYPE_GANG9 = 15,
	PEDTYPE_MEDIC = 16,
	PEDTYPE_FIRE = 17,
	PEDTYPE_CRIMINAL = 18,
	PEDTYPE_BUM = 19,
	PEDTYPE_PROSTITUTE = 20,
	PEDTYPE_SPECIAL = 21,
	PEDTYPE_DUMMY = 22
};
