/*
Plugin-SDK (Grand Theft Auto) header file
Authors: GTA Community. See more here
https://github.com/DK22Pac/plugin-sdk
Do not delete this comment block. Respect others' work!
*/
#pragma once

enum eWeaponType : unsigned __int32
{
    WEAPON_UNARMED = 0x0,
    WEAPON_BRASSKNUCKLE = 0x1,
    WEAPON_SCREWDRIVER = 0x2,
    WEAPON_GOLFCLUB = 0x3,
    WEAPON_NIGHTSTICK = 0x4,
    WEAPON_KNIFE = 0x5,
    WEAPON_BASEBALLBAT = 0x6,
    WEAPON_HAMMER = 0x7,
    WEAPON_CLEAVER = 0x8,
    WEAPON_MACHETE = 0x9,
    WEAPON_KATANA = 0xA,
    WEAPON_CHAINSAW = 0xB,
    WEAPON_GRENADE = 0xC,
    WEAPON_DETONATEGRENADE = 0xD,
    WEAPON_TEARGAS = 0xE,
    WEAPON_MOLOTOV = 0xF,
    WEAPON_ROCKET = 0x10,
    WEAPON_COLT45 = 0x11,
    WEAPON_PYTHON = 0x12,
    WEAPON_SHOTGUN = 0x13,
    WEAPON_SPAS12SHOTGUN = 0x14,
    WEAPON_STUBBYSHOTGUN = 0x15,
    WEAPON_TEC9 = 0x16,
    WEAPON_UZI_C = 0x17,
    WEAPON_SILENCEDINGRAM = 0x18,
    WEAPON_MP5 = 0x19,
    WEAPON_M4 = 0x1A,
    WEAPON_RUGER = 0x1B,
    WEAPON_SNIPERRIFLE = 0x1C,
    WEAPON_LASERSCOPE = 0x1D,
    WEAPON_ROCKETLAUNCHER = 0x1E,
    WEAPON_FLAMETHROWER = 0x1F,
    WEAPON_M60 = 0x20,
    WEAPON_MINIGUN = 0x21,
    WEAPON_DETONATOR = 0x22,
    WEAPON_HELICANNON = 0x23,
    WEAPON_CAMERA = 0x24
};