/*
Plugin-SDK (Grand Theft Auto Vice City) header file
Authors: GTA Community. See more here
https://github.com/DK22Pac/plugin-sdk
Do not delete this comment block. Respect others' work!
*/
#pragma once

enum eParticleObjectType
{
	POBJECT_PAVEMENT_STEAM = 0,
	POBJECT_PAVEMENT_STEAM_SLOWMOTION = 1,
	POBJECT_WALL_STEAM = 2,
	POBJECT_WALL_STEAM_SLOWMOTION = 3,
	POBJECT_DARK_SMOKE = 4,
	POBJECT_FIRE_HYDRANT = 5,
	POBJECT_CAR_WATER_SPLASH = 6,
	POBJECT_PED_WATER_SPLASH = 7,
	POBJECT_SPLASHES_AROUND = 8,
	POBJECT_SMALL_FIRE = 9,
	POBJECT_BIG_FIRE = 10,
	POBJECT_DRY_ICE = 11,
	POBJECT_DRY_ICE_SLOWMOTION = 12,
	POBJECT_WATER_FOUNTAIN_VERT = 13,
	POBJECT_WATER_FOUNTAIN_HORIZ = 14,
	POBJECT_FIRE_TRAIL = 15,
	POBJECT_SMOKE_TRAIL = 16,
	POBJECT_FIREBALL_AND_SMOKE = 17,
	POBJECT_ROCKET_TRAIL = 18,
	POBJECT_EXPLOSION_ONCE = 19,
	POBJECT_CATALINAS_GUNFLASH = 20,
	POBJECT_CATALINAS_SHOTGUNFLASH = 21
};