/*
Plugin-SDK (Grand Theft Auto Vice City) header file
Authors: GTA Community. See more here
https://github.com/DK22Pac/plugin-sdk
Do not delete this comment block. Respect others' work!
*/
#pragma once

enum ePickupType
{
	PICKUP_NONE = 0,
	PICKUP_IN_SHOP = 1,
	PICKUP_ON_STREET = 2,
	PICKUP_ONCE = 3,
	PICKUP_ONCE_TIMEOUT = 4,
	PICKUP_ONCE_TIMEOUT_SLOW = 5,
	PICKUP_COLLECTABLE1 = 6,
	PICKUP_IN_SHOP_OUT_OF_STOCK = 7,
	PICKUP_MONEY = 8,
	PICKUP_MINE_INACTIVE = 9,
	PICKUP_MINE_ARMED = 10,
	PICKUP_NAUTICAL_MINE_INACTIVE = 11,
	PICKUP_NAUTICAL_MINE_ARMED = 12,
	PICKUP_FLOATINGPACKAGE = 13,
	PICKUP_FLOATINGPACKAGE_FLOATING = 14,
	PICKUP_ON_STREET_SLOW = 15,
	PICKUP_ASSET_REVENUE = 16,
	PICKUP_PROPERTY_LOCKED = 17,
	PICKUP_PROPERTY_FORSALE = 18
};