/*
Plugin-SDK (Grand Theft Auto Vice City) header file
Authors: GTA Community. See more here
https://github.com/DK22Pac/plugin-sdk
Do not delete this comment block. Respect others' work!
*/
#pragma once

enum eWaitState
{
	WAITSTATE_FALSE = 0,
	WAITSTATE_TRAFFIC_LIGHTS = 1,
	WAITSTATE_CROSS_ROAD = 2,
	WAITSTATE_CROSS_ROAD_LOOK = 3,
	WAITSTATE_LOOK_PED = 4,
	WAITSTATE_LOOK_SHOP = 5,
	WAITSTATE_LOOK_ACCIDENT = 6,
	WAITSTATE_FACEOFF_GANG = 7,
	WAITSTATE_DOUBLEBACK = 8,
	WAITSTATE_HITWALL = 9,
	WAITSTATE_TURN180 = 10,
	WAITSTATE_SURPRISE = 11,
	WAITSTATE_STUCK = 12,
	WAITSTATE_LOOK_ABOUT = 13,
	WAITSTATE_PLAYANIM_DUCK = 14,
	WAITSTATE_PLAYANIM_COWER = 15,
	WAITSTATE_PLAYANIM_TAXI = 16,
	WAITSTATE_PLAYANIM_HANDSUP = 17,
	WAITSTATE_PLAYANIM_HANDSCOWER = 18,
	WAITSTATE_PLAYANIM_CHAT = 19,
	WAITSTATE_FINISH_FLEE = 20,
	WAITSTATE_SIT_DOWN = 21,
	WAITSTATE_SIT_DOWN_RVRS = 22,
	WAITSTATE_SIT_UP = 23,
	WAITSTATE_SIT_IDLE = 24,
	WAITSTATE_USE_ATM = 25,
	WAITSTATE_SUN_BATHE_PRE = 26,
	WAITSTATE_SUN_BATHE_DOWN = 27,
	WAITSTATE_SUN_BATHE_IDLE = 28,
	WAITSTATE_RIOT = 29,
	WAITSTATE_FAST_FALL = 30,
	WAITSTATE_BOMBER = 31,
	WAITSTATE_STRIPPER = 32,
	WAITSTATE_GROUND_ATTACK = 33,
	WAITSTATE_LANCESITTING = 34,
	WAITSTATE_PLAYANIM_HANDSUP_SIMPLE = 35
};