/*
Plugin-SDK (Grand Theft Auto Vice City) header file
Authors: GTA Community. See more here
https://github.com/DK22Pac/plugin-sdk
Do not delete this comment block. Respect others' work!
*/
#pragma once

enum eWeaponType : unsigned int
{
	WEAPONTYPE_UNARMED = 0,
	WEAPONTYPE_BRASSKNUCKLE = 1,
	WEAPONTYPE_SCREWDRIVER = 2,
	WEAPONTYPE_GOLFCLUB = 3,
	WEAPONTYPE_NIGHTSTICK = 4,
	WEAPONTYPE_KNIFE = 5,
	WEAPONTYPE_BASEBALLBAT = 6,
	WEAPONTYPE_HAMMER = 7,
	WEAPONTYPE_CLEAVER = 8,
	WEAPONTYPE_MACHETE = 9,
	WEAPONTYPE_KATANA = 10,
	WEAPONTYPE_CHAINSAW = 11,
	WEAPONTYPE_GRENADE = 12,
	WEAPONTYPE_DETONATOR_GRENADE = 13,
	WEAPONTYPE_TEARGAS = 14,
	WEAPONTYPE_MOLOTOV = 15,
	WEAPONTYPE_ROCKET = 16,
	WEAPONTYPE_PISTOL = 17,
	WEAPONTYPE_PYTHON = 18,
	WEAPONTYPE_SHOTGUN = 19,
	WEAPONTYPE_SPAS12_SHOTGUN = 20,
	WEAPONTYPE_STUBBY_SHOTGUN = 21,
	WEAPONTYPE_TEC9 = 22,
	WEAPONTYPE_UZI = 23,
	WEAPONTYPE_SILENCED_INGRAM = 24,
	WEAPONTYPE_MP5 = 25,
	WEAPONTYPE_M4 = 26,
	WEAPONTYPE_RUGER = 27,
	WEAPONTYPE_SNIPERRIFLE = 28,
	WEAPONTYPE_LASERSCOPE = 29,
	WEAPONTYPE_ROCKETLAUNCHER = 30,
	WEAPONTYPE_FLAMETHROWER = 31,
	WEAPONTYPE_M60 = 32,
	WEAPONTYPE_MINIGUN = 33,
	WEAPONTYPE_DETONATOR = 34,
	WEAPONTYPE_HELICANNON = 35,
	WEAPONTYPE_CAMERA = 36,
	WEAPONTYPE_PAD37 = 37,
	WEAPONTYPE_ARMOUR = 38,
	WEAPONTYPE_RAMMEDBYCAR = 39,
	WEAPONTYPE_RUNOVERBYCAR = 40,
	WEAPONTYPE_EXPLOSION = 41,
	WEAPONTYPE_UZI_DRIVEBY = 42,
	WEAPONTYPE_DROWNING = 43,
	WEAPONTYPE_FALL = 44,
	WEAPONTYPE_UNIDENTIFIED = 45,
	WEAPONTYPE_ANYMELEE = 46,
	WEAPONTYPE_ANYWEAPON = 47
};