# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build using numake

on:
  push:
    branches:
      - "master"

  workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: plugin.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read

jobs:
  build_and_release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - run: "sudo apt-get install g++-mingw-w64-i686 binutils-mingw-w64-i686"

      - name: Download numake
        run: |
          gh release download indev -R juicermv/numake --dir "${{runner.temp}}"
          chmod a+x ${{runner.temp}}/numake

      - name: Build using numake
        run: ${{runner.temp}}/numake build all -w ${{github.workspace}}

      - run: cp -r .numake/out .

      - name: Archive build
        working-directory: ${{github.workspace}}
        run: zip -9 -Zb -r ${{github.workspace}}/release.zip .

      - name: Create release
        run: gh release create "$(git rev-parse --short HEAD)_$(date +%H-%M)" --generate-notes

      - name: Upload build to release
        run: gh release upload "$(git rev-parse --short HEAD)_$(date +%H-%M)" ${{github.workspace}}/release.zip
