name: Sync 

on:
  schedule:
    - cron: 0 0 * * * 
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: write

jobs:
  sync:
    runs-on: self-hosted

    steps:
      - run: gh repo sync juicermv/plugin-sdk --force --source dk22pac/plugin-sdk --branch fixes
        
