name: Sync 

on:
  schedule:
    - cron: 0 0 * * * 
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: git stash --all

      - run: gh repo sync
        
